{
  "openapi": "3.0.0",
  "info": {
    "title": "Chatee API",
    "version": "1.0.0",
    "description": "API used for chatee application"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/auth/signup/": {
      "post": {
        "description": "Sign up user for the application",
        "tags": [
          "auth"
        ],
        "requestBody": {
          "description": "Sign up body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserSchema"
              },
              "example": {
                "email": "test.user@mail.com",
                "password": "test_test",
                "name": "steve jobs"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User has been signed up",
            "content": {
              "appication/json": {
                "example": {
                  "status": 200,
                  "logged": true,
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
                  "message": "Sign up successfull"
                }
              }
            }
          },
          "400": {
            "description": "Sign up failed",
            "content": {
              "application/json": {
                "example": {
                  "status": 400,
                  "logged": false,
                  "message": "Email already exists"
                }
              }
            }
          }
        }
      }
    },
    "/auth/login/": {
      "post": {
        "description": "Login user to the application",
        "tags": [
          "auth"
        ],
        "requestBody": {
          "description": "login body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserSchema"
              },
              "example": {
                "email": "test.user@mail.com",
                "password": "test_test"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User has been logged in",
            "content": {
              "appication/json": {
                "example": {
                  "status": 200,
                  "logged": true,
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
                  "message": "Login successfull"
                }
              }
            }
          },
          "401": {
            "description": "Not logged, invalid credentials",
            "content": {
              "application/json": {
                "example": {
                  "status": 401,
                  "logged": false,
                  "message": "Invalid credentials"
                }
              }
            }
          }
        }
      }
    },
    "/v1/chats/all": {
      "get": {
        "description": "Get chat info for all chats user is in",
        "tags": [
          "chats"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Returned chat info",
            "content": {
              "application/json": {
                "example": {
                  "messages": [],
                  "members": [],
                  "membersTyping": [],
                  "creator": "ethan",
                  "createdDate": "1-2-3"
                }
              }
            }
          }
        }
      }
    },
    "/v1/chats/:chatid": {
      "get": {
        "description": "Get full chat messages and info",
        "tags": [
          "chats"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Returned chat info and messages",
            "content": {
              "application/json": {
                "example": {
                  "messages": [],
                  "completeMessages": [],
                  "members": [],
                  "membersTyping": [],
                  "creator": "ethan",
                  "createdDate": "1-2-3"
                }
              }
            }
          }
        }
      }
    },
    "/v1/chats": {
      "post": {
        "description": "Create a new chat",
        "tags": [
          "chats"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Returned new chat",
            "content": {
              "application/json": {
                "example": {
                  "messages": [],
                  "members": [
                    "jake@mail.com"
                  ],
                  "membersTyping": [],
                  "_id": "awlkjdaolkwdjawio9du90",
                  "creator": "jake@mail.com",
                  "createdDate": "2019-11-02T00:23:12.000Z"
                }
              }
            }
          }
        }
      }
    },
    "/v1/chats/": {
      "delete": {
        "description": "Delete chat",
        "tags": [
          "chats"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Returned new chat",
            "content": {
              "application/json": {
                "example": {
                  "messages": [],
                  "members": [
                    "jake@mail.com"
                  ],
                  "membersTyping": [],
                  "_id": "awlkjdaolkwdjawio9du90",
                  "creator": "jake@mail.com",
                  "createdDate": "2019-11-02T00:23:12.000Z"
                }
              }
            }
          }
        }
      }
    },
    "/v1/chats/invite": {
      "post": {
        "description": "Invite a member to a chat",
        "tags": [
          "chats"
        ],
        "requestBody": {
          "description": "Chat invite body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ChatSchema"
              },
              "example": {
                "newuser": "stevejobs@apple.com",
                "chatid": "chatabcd"
              }
            }
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "User invited to chat"
          }
        }
      }
    },
    "/v1/chats/handleInvite": {
      "post": {
        "description": "Handle response to chat invite",
        "tags": [
          "chats"
        ],
        "requestBody": {
          "description": "Chat invite request body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ChatSchema"
              },
              "example": {
                "accept": true,
                "chatid": "1234chatabcd"
              }
            }
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Returned updated user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserSchema"
                },
                "example": {
                  "chats": [
                    "1234chatabcd"
                  ],
                  "chatRequests": [],
                  "friends": [],
                  "incomingFriendRequests": [],
                  "outgoingFriendRequests": [
                    "jake@mail.com"
                  ],
                  "email": "example@mail.com",
                  "profile": []
                }
              }
            }
          }
        }
      }
    },
    "/v1/chats/remove": {
      "post": {
        "description": "Remove a member from a chat",
        "tags": [
          "chats"
        ],
        "requestBody": {
          "description": "Chat remove body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ChatSchema"
              },
              "example": {
                "removeuser": "stevejobs@apple.com",
                "chatid": "chatabcd"
              }
            }
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "User removed from chat"
          }
        }
      }
    },
    "/v1/messages/": {
      "post": {
        "description": "Create a new message",
        "tags": [
          "messages"
        ],
        "requestBody": {
          "description": "Message body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MessageSchema"
              },
              "example": {
                "message": {
                  "type": "text",
                  "message": "asdf hi"
                },
                "chatid": "1234chatid"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Message created",
            "content": {
              "appication/json": {
                "example": {
                  "status": 200,
                  "_id": "messageid1234",
                  "author": "steve@apple.com",
                  "type": "text",
                  "message": "asdf hi",
                  "createdDate": "2019-11-02T02:22:25.000Z",
                  "editDate": "2019-11-02T02:22:25.000Z"
                }
              }
            }
          }
        }
      },
      "patch": {
        "description": "Edit a message",
        "tags": [
          "messages"
        ],
        "requestBody": {
          "description": "Message body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MessageSchema"
              },
              "example": {
                "message": {
                  "type": "text",
                  "message": "asdf hi"
                },
                "messageid": "messageid1234"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Message modified",
            "content": {
              "appication/json": {
                "example": {
                  "status": 200,
                  "_id": "messageid1234",
                  "author": "steve@apple.com",
                  "type": "text",
                  "message": "asdf hi",
                  "createdDate": "2019-11-02T02:22:25.000Z",
                  "editDate": "2019-11-02T02:22:25.000Z"
                }
              }
            }
          }
        }
      }
    },
    "/v1/messages/{id}": {
      "delete": {
        "description": "Delete a message",
        "tags": [
          "messages"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "the unique messageid",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Message modified",
            "content": {
              "appication/json": {
                "example": {
                  "status": 200,
                  "_id": "messageid1234",
                  "author": "steve@apple.com",
                  "type": "text",
                  "message": "asdf hi",
                  "createdDate": "2019-11-02T02:22:25.000Z",
                  "editDate": "2019-11-02T02:22:25.000Z"
                }
              }
            }
          }
        }
      }
    },
    "/v1/users/all": {
      "get": {
        "description": "Get all users",
        "tags": [
          "users"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Returned users",
            "content": {
              "application/json": {
                "example": {
                  "users": []
                }
              }
            }
          }
        }
      }
    },
    "/v1/users/:userid": {
      "get": {
        "description": "Get user by userid",
        "tags": [
          "users"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userid",
            "description": "the unique userid",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returned user",
            "content": {
              "application/json": {
                "example": {
                  "friends": [
                    "steve@mail.com"
                  ],
                  "email": "jake123@mail.com",
                  "profile": [
                    "profileData"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/v1/users/": {
      "delete": {
        "description": "Delete user",
        "tags": [
          "users"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Returned deleted user",
            "content": {
              "application/json": {
                "example": {
                  "chats": [],
                  "chatRequests": [],
                  "friends": [],
                  "incomingFriendRequests": [],
                  "outgoingFriendRequests": [],
                  "email": "example@mail.com",
                  "profile": []
                }
              }
            }
          }
        }
      }
    },
    "/v1/users/friendRequest": {
      "post": {
        "description": "Send a friend request to another user",
        "tags": [
          "users"
        ],
        "requestBody": {
          "description": "Friend request body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserSchema"
              },
              "example": {
                "potentialFriend": "jake@mail.com"
              }
            }
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Returned updated user",
            "content": {
              "application/json": {
                "example": {
                  "chats": [],
                  "chatRequests": [],
                  "friends": [],
                  "incomingFriendRequests": [],
                  "outgoingFriendRequests": [
                    "jake@mail.com"
                  ],
                  "email": "example@mail.com",
                  "profile": []
                }
              }
            }
          }
        }
      }
    },
    "/v1/users/handleFriend": {
      "post": {
        "description": "Handle a friend request from another user",
        "tags": [
          "users"
        ],
        "requestBody": {
          "description": "Handle friend request body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserSchema"
              },
              "example": {
                "potentialFriend": "example@mail.com",
                "accept": true
              }
            }
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Returned updated user",
            "content": {
              "application/json": {
                "example": {
                  "chats": [],
                  "chatRequests": [],
                  "friends": [
                    "example@mail.com"
                  ],
                  "incomingFriendRequests": [],
                  "outgoingFriendRequests": [],
                  "email": "steve@mail.com",
                  "profile": []
                }
              }
            }
          }
        }
      }
    },
    "/v1/users/removeFriend": {
      "post": {
        "description": "Handle removing a friend",
        "tags": [
          "users"
        ],
        "requestBody": {
          "description": "Remove friend request body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserSchema"
              },
              "example": {
                "friend": "example@mail.com"
              }
            }
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Returned updated user",
            "content": {
              "application/json": {
                "example": {
                  "chats": [],
                  "chatRequests": [],
                  "friends": [],
                  "incomingFriendRequests": [],
                  "outgoingFriendRequests": [],
                  "email": "steve@mail.com",
                  "profile": []
                }
              }
            }
          }
        }
      }
    },
    "/v1/users/updateProfile": {
      "post": {
        "description": "Handle updating a profile",
        "tags": [
          "users"
        ],
        "requestBody": {
          "description": "Update profile request body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserSchema"
              },
              "example": {
                "profile": [
                  "profileData"
                ]
              }
            }
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Updated user",
            "content": {
              "application/json": {
                "example": {
                  "chats": [],
                  "chatRequests": [],
                  "friends": [],
                  "incomingFriendRequests": [],
                  "outgoingFriendRequests": [],
                  "email": "steve@mail.com",
                  "profile": [
                    "new and exciting"
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ChatSchema": {
        "required": [
          "creator"
        ],
        "properties": {
          "messages": {
            "type": "array"
          },
          "members": {
            "type": "array"
          },
          "lastMessage": {
            "type": "string"
          },
          "membersTyping": {
            "type": "array"
          }
        }
      },
      "MessageSchema": {
        "required": [
          "author"
        ],
        "properties": {
          "type": {
            "type": "string"
          },
          "author": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "createdDate": {
            "type": "array"
          },
          "editDate": {
            "type": "string"
          }
        }
      },
      "UserSchema": {
        "required": [
          "email"
        ],
        "properties": {
          "email": {
            "type": "string"
          },
          "profile": {
            "type": "object"
          },
          "password": {
            "type": "string"
          },
          "chats": {
            "type": "array"
          },
          "friends": {
            "type": "array"
          }
        }
      },
      "Error": {
        "type": "object",
        "required": [
          "status",
          "message"
        ],
        "properties": {
          "status": {
            "type": "integer",
            "description": "HTTP status code",
            "example": 200
          },
          "message": {
            "type": "string",
            "description": "Error description",
            "example": "User created"
          }
        }
      }
    },
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "x-access-token"
      }
    }
  },
  "tags": []
}